### ISSUE TITLE
Unable to run packaging/build-bayeslite-venv.sh on ProbComp

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/packaging#12]
set -eu command breaks ssh connection.

**Comment by riastradh-probcomp** [comment]
How did you run it?

**Comment by leocasarsa** [comment]
Also I'd recommend adding a line `pip install --upgrade pip`, as older versions of pip don't have the `--no-cache-dir` option.

**Comment by leocasarsa** [comment]
`\bin\bash build-bayeslite-venv.sh bdb`

**Comment by riastradh-probcomp** [comment]
Did you previously try `. ./build-bayeslite-venv.sh` or `source build-bayeslite-venv.sh`?  If so, the `set -eu` will apply to your interactive shell -- not just to the bash subprocess -- and remain active in your interactive shell until you log out and log back in again.  Otherwise, this is quite a trick -- I would be interested in seeing a reproduction!

(This script is definitely not for use with `.` or `source`.)

**Comment by leocasarsa** [comment]
You are right, I had run it with `.`

I did `/bin/bash build-bayeslite-venv.sh bdb` now and it only complains of pip.

```
Usage:   
  pip <command> [options]

no such option: --no-cache-dir
```
