### ISSUE TITLE
build-bayeslite-venv.sh: List of necessary updates

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/packaging#15]
- update python to 2.7.11
- update pip to version compatible with --no-cache-dir
- change standard version install to head (and maybe delete latest as it's deprecated)

**Comment by gregory-marton** [comment]
- disagree with changing default from latest to head. Latest is the supported version, and folks here should be on board with bothering to type "head" as the arg.
- can't really make updating python part of the script — that's too platform specific. 
- Will make upgrading pip and setuptools part of the script.

Python and pip are now up to date on the probcomps.

**Comment by leocasarsa** [comment]
Just reminding you that the current latest is not really the supported version, as it downloads unsupported versions of crosscat and bayeslite. Latest is currently broken (returning cryptic error messages when initializing a metamodel in bayeslite).

**Comment by leocasarsa** [comment]
Re updating python, if it is not possible to update it, could we at least issue a warning (with a "continue? (yes/no)" option) when people try to install bayeslite and their python version is not 2.7.11?

**Comment by riastradh-probcomp** [comment]
Date: Sat, 07 May 2016 12:22:24 -0700
   From: leocasarsa notifications@github.com

   Re updating python, if it is not possible to update it, could we at
   least issue a warning (with a "continue? (yes/no)" option) when
   people try to install bayeslite and their python version is not
   2.7.11?

What is the problem with <2.7.11?  There's an open issue about this:
<https://github.com/probcomp/bdbcontrib/issues/132>, but I can't
figure out what anyone actually needs from 2.7.11 that is not in
2.7.6.  If you know, please respond to that issue!

**Comment by gregory-marton** [comment]
Starting to change my mind about the default being head. Let's talk more about that.

I think the rest of these are done now, via build_venv.py
Take a look through the options there and see if there's something you'd like to have that's missing?

Incidentally the older versions are untested and probably broken because the package dependencies are wrong. I think I'm just going to remove them, but wanted to have something of a record there. Alternately, I could take the time to check that they all work.
