### ISSUE TITLE
lab/bin/activate: line 8: _OLD_VIRTUAL_PATH: unbound variable

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/packaging#9]
Same error raised when running in shell

```
set -eu
$venv_dir/bin/activate
```

Error disappears if I remove `set -eu`

**Comment by riastradh-probcomp** [comment]
I assume you meant `. $venv_dir/bin/activate`?  Yes, it looks like the activate script is not set up to cope with `set -eu`.

(`set -eu` means please fail immediately if a subcommand in this script fails (`set -e`), and please fail immediately if you try to use an undefined variable instead of just giving the empty string (`set -u`).  It's a good practice to use it for every shell script you write, because it is much less error-prone and causes mistakes to fail noisily earlier -- but some people don't write shell scripts that work with it, such as the virtualenv activate scripts.)
